# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('link', models.CharField(max_length=200, verbose_name='\u539f\u6587\u5730\u5740')),
                ('blog_type', models.IntegerField(choices=[(1, '\u539f\u521b'), (2, '\u8f6c\u8f7d')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nblog.Tags'),
        ),
    ]
