# Generated by Django 2.2.6 on 2019-10-17 04:24

from django.db import migrations, models
import mdeditor.fields
import nblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='原文地址')),
                ('blog_type', models.IntegerField(choices=[(1, '原创'), (2, '转载')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tags', models.ManyToManyField(default=nblog.models.m2mdefault, to='nblog.Tags')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
