# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import nblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(default=nblog.models.m2mdefault, to='nblog.Tags'),
        ),
    ]
