# Generated by Django 2.2.6 on 2019-10-16 07:22

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0002_auto_20170927_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='blog_type',
            field=models.IntegerField(choices=[(1, '原创'), (2, '转载')], default=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='原文地址'),
        ),
    ]
